
services:
  # El "motor" de nuestra base de datos
  db:
    image: postgres:15-alpine
    container_name: hotel_db
    restart: always
    environment:
      POSTGRES_USER: admin_hotel
      POSTGRES_PASSWORD: password123 
      POSTGRES_DB: hotel_db
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

# Aquí se guardarán los datos físicamente en tu PC
volumes:
  db_data: